name: Bug Report
description: File a bug report to help us improve
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        **Desktop (please complete the following information):**
        - OS: [e.g. Windows 11, Ubuntu 22.04]
        - Python version: [e.g. 3.11.5]
        - Control version: [e.g. 0.1.0]
        - Docker version: [e.g. 24.0.5]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: |
        ```
        Paste any relevant logs here
        ```
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Bug is reproducible
        - label: Root cause is identified
        - label: Fix is implemented
        - label: Tests are added/updated
        - label: Documentation is updated
