name: control-ci

on:
  push:
    branches: [ main, work/daily ]
  pull_request:
    branches: [ main, work/daily ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Verify Markdown spacing
        run: |
          bash tools/verify-markdown.sh

      - name: OpenAPI sync verify (control vs certeus)
        run: |
          bash tools/openapi-sync.sh verify
      - name: CI OK
        run: echo OK
