name: control-ci

on:
  push:
    branches: [ main, work/daily ]
  pull_request:
    branches: [ main, work/daily ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: CI OK
        run: echo OK
